@startuml move_player_with_pencil_raised

activate ":Game"
    ":Game" -> "player:Player": run(sequence)
    activate "player:Player"
        "player:Player" -> "sequence:Sequence": run(player)
        activate "sequence:Sequence"
            "sequence:Sequence" -> ":RaisePencilAction": execute(player)
            activate ":RaisePencilAction"
                ":RaisePencilAction" -> "player:Player": raisePencil()
                activate "player:Player"
                    "player:Player" -> ":Pencil": raise()
                    activate ":Pencil"
                        create "state:RaisedPencilState"
                            ":Pencil" -> "state:RaisedPencilState": new()
                    deactivate ":Pencil"
                deactivate "player:Player"
            deactivate ":RaisePencilAction"
            "sequence:Sequence" -> ":MoveDownAction": execute(player)
            activate ":MoveDownAction"
                ":MoveDownAction" -> "player:Player": move(direction)
                activate "player:Player"
                    "player:Player" -> ":Pencil": draw(oldPos, newPos)
                    activate ":Pencil"
                        ":Pencil" -> "state:RaisedPencilState": draw(start, finish)
                        activate "state:RaisedPencilState"
                            create "blank:Blank"
                            "state:RaisedPencilState" -> "blank:Blank": new()
                        return blank
                    return blank
                    "player:Player" -> ":Drawing": addShape(blank)
                    activate ":Drawing"
                    deactivate ":Drawing"
                deactivate "player:Player"
            deactivate ":MoveDownAction"
        deactivate "sequence:Sequence"
    return drawing
deactivate ":Game"

@enduml