@startuml move_left_do_action

activate Game
Game -> Player: do(moveLeft)
activate Player

Player -> Movement: move(left, oldCoordenate)
activate Movement
Movement -> Position: nextPosition(left, oldCoordenate)
activate Position
Position -> Grid: isInGrid(oldCoordenate)
activate Grid
return newCoordenate
return newCoordenate
return newCoordenate

Player -> Pencil: draw(oldCoordenate,\n newCoordenate)
activate Pencil
Pencil -> LoweredPencilState: draw(oldCoordenate, \n newCoordenate)
activate LoweredPencilState
LoweredPencilState -> Line: <<create>>
activate Line
return line
return line
return line
return line

Game -> Whiteboard: drawLine(line)
activate Whiteboard
Whiteboard -> Drawing: drawLine(line)
activate Drawing
deactivate Drawing
deactivate Whiteboard
deactivate Player
deactivate Game






@enduml