@startuml move_left

actor User

activate User

User -> Game: run()
activate Game
Game -> Workspace: compile()
activate Workspace
Workspace -> Algorithm: compile()
activate Algorithm
create Sequence
Algorithm -> Sequence: <<create>>
activate Sequence
return sequence
return sequence
return sequence

Game -> Game: do(sequence)
activate Game
loop for every action in sequence
Game -> Player: do(action)
activate Player
deactivate Player
Game -> Whiteboard: drawLine(line)
activate Whiteboard
deactivate Whiteboard
end
deactivate Game
deactivate Game
deactivate User


@enduml